##\
# This file is a part of the phpMussel\Web package.
# Homepage: https://phpmussel.github.io/
#
# PHPMUSSEL COPYRIGHT 2013 AND BEYOND BY THE PHPMUSSEL TEAM.
#
# License: GNU/GPLv2
# @see LICENSE.txt
#
# This file: Configuration defaults file (last modified: 2020.06.22).
##/

web:
 uploads_log:
  type: "string"
  default: ""
 forbid_on_block:
  type: "bool"
  default: true
 max_uploads:
  type: "int"
  default: 10
 ignore_upload_errors:
  type: "bool"
  default: false
 theme:
  type: "string"
  default: "default"
  preview: "allow_other"
  allow_other: true
  choices:
   default: "Default"
   rbi: "Red-Blue Inverted"
   slate: "Slate"
   bluemetal: "Blue Metal"
   moss: "Moss"
   fullmoon: "Full Moon"
  choice_filter: "FilterTheme"
 magnification:
  type: "float"
  step: "any"
  default: 1
legal:
 privacy_policy:
  type: "url"
  default: ""
  autocomplete: "url"
